version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    network_mode: "host"
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  mysql:
    image: mysql:latest
    container_name: mysql
    network_mode: "host"
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      #MYSQL_DATABASE: db5
      #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    network_mode: "host"
    hostname: localhost
    ports:
      - 27017:27017
  config-server:
    image: config-server
    build: config-server/
    container_name: config-server
    network_mode: "host"
    hostname: localhost
    restart: always
    ports:
      - 8888:8888
  eureka-server:
    image: eureka-server
    build: eureka-server/
    container_name: eureka-server
    network_mode: "host"
    hostname: localhost
    restart: always
    ports:
      - 8761:8761
    depends_on:
      - config-server
  api-gateway:
    image: api-gateway
    build: api-gateway/
    container_name: api-gateway
    network_mode: "host"
    hostname: localhost
    ports:
      - 8585:8585
    depends_on:
      - eureka-server
  user-service:
    image: user-service
    container_name: user-service
    build: user-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 9000:9000
    depends_on:
      - mongodb
      - rabbitmq
      - config-server
      - eureka-server
  authentication-service:
    image: authentication-service
    container_name: authentication-service
    build: authentication-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 9010:9010
    depends_on:
      - mysql
      - rabbitmq
      - config-server
      - eureka-server
  appointment-service:
    image: appointment-service
    container_name: appointment-service
    build: appointment-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 8060:8060
    depends_on:
      - mongodb
      - rabbitmq
      - config-server
      - eureka-server
  email-service:
    image: email-service
    container_name: email-service
    build: email-service/
    hostname: localhost
    network_mode: "host"
    ports:
      - 8075:8075
    depends_on:
      - rabbitmq
      - config-server
      - eureka-server
  webapp:
    image: webapp
    container_name: webapp
    build: webapp/
    hostname: localhost
    network_mode: "host"
    ports:
      - 4200:4200
    depends_on:
      - config-server
      - eureka-server
      - api-gateway


